name: 'Pull Request Linter Action'
description: 'Lint pull request names with commitlint'
author: 'Patrick Muff'
inputs:
  configuration-path:
    description: 'The path for the commitlint configurations'
    required: false
    default: './commitlint.config.js'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'users'
  color: 'blue'
